FROM bearstech/debian:stretch

RUN apt-get update && \
    apt-get install -y \
        python3 \
    && rm -rf /var/lib/apt/lists/* \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3 1

ENV LANG=C.UTF-8
