FROM bearstech/debian:stretch

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        python2.7-dev \
        python-pip \
        python-wheel \
    && rm -rf /var/lib/apt/lists/*

RUN pip install virtualenv
