FROM bearstech/debian:stretch

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        python2.7-dev \
        python-pip \
        python-wheel \
    && rm -rf /var/lib/apt/lists/* \
    && update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

RUN pip install virtualenv
