FROM bearstech/debian:stretch

ENV LANG=C.UTF-8

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                python3 \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  update-alternatives --install /usr/bin/python python /usr/bin/python3 1
