FROM bearstech/debian-dev:buster

ENV LANG=C.UTF-8
ENV PIP_CACHE_DIR=/.cache/pip

RUN set -eux \
    &&  mkdir -p /.cache/pip \
    &&  export http_proxy=${HTTP_PROXY} \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                  python2.7-dev \
                  python-pip \
		  python-setuptools \
                  python-wheel \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1 \
    &&  pip install virtualenv

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL \
    com.bearstech.image.revision_date=${GIT_DATE} \
    org.opencontainers.image.authors=Bearstech \
    org.opencontainers.image.revision=${GIT_VERSION} \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.url=https://github.com/factorysh/docker-python \
    org.opencontainers.image.source=https://github.com/factorysh/docker-python/blob/${GIT_VERSION}/Dockerfile.27-dev
