FROM bearstech/python:3

ENV PIP_CACHE_DIR=/.cache/pip

RUN set -eux \
    &&  mkdir -p /.cache/pip \
    &&  update-alternatives --remove python /usr/bin/python3 \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                build-essential \
                git \
                mercurial \
                mercurial-common \
                python3-dev \
                python3-pip \
                python3-setuptools \
                python3-venv \
                python3-wheel \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  update-alternatives --install /usr/bin/python python /usr/bin/python3 1
