FROM bearstech/pypy:5.6

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                    build-essential \
                    ca-certificates \
                    pypy-dev \
                    pypy-setuptools \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  easy_install-pypy pip virtualenv wheel
