FROM bearstech/debian:stretch

RUN apt-get update && \
    apt-get install -y \
        build-essential \
	ca-certificates \
        pypy-dev \
        pypy-setuptools \
    && rm -rf /var/lib/apt/lists/* \
    && update-alternatives --install /usr/bin/python python /usr/bin/pypy 1

ENV LANG=C.UTF-8

RUN easy_install-pypy pip virtualenv wheel
