FROM bearstech/debian:stretch

ENV LANG=C.UTF-8

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends\
                    pypy \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  update-alternatives --install /usr/bin/python python /usr/bin/pypy 1

ARG GIT_VERSION
LABEL com.bearstech.source.python=https://github.com/factorysh/docker-python/commit/${GIT_VERSION}

ARG GIT_DATE
LABEL com.bearstech.date.python=${GIT_DATE}
