FROM bearstech/debian:stretch

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        pypy-dev \
        pypy-setuptools \
    && rm -rf /var/lib/apt/lists/*

RUN easy_install-pypy pip virtualenv wheel
