FROM bearstech/debian:stretch
ARG PYPY_VERSION

RUN set -eux \
    && echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list \
    &&  apt-get update \
    &&  apt-get -t stretch-backports install -y --no-install-recommends \
                  pypy \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  update-alternatives --install /usr/bin/python python /usr/bin/pypy 1

