FROM bearstech/debian-dev:stretch

ENV LANG=C.UTF-8
ENV PIP_CACHE_DIR=/.cache/pip

RUN set -eux \
    &&  mkdir -p /.cache/pip \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                  python2.7-dev \
                  python-pip \
                  python-wheel \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1 \
    &&  pip install virtualenv

ARG GIT_VERSION
LABEL com.bearstech.source.python=https://github.com/factorysh/docker-python/commit/${GIT_VERSION}

ARG GIT_DATE
LABEL com.bearstech.date.python=${GIT_DATE}
