FROM bearstech/debian-dev:stretch
ARG PYPY_VERSION

ENV LANG=C.UTF-8
ENV PIP_CACHE_DIR=/.cache/pip

RUN set -eux \
    && echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list \
    &&  apt-get update \
    &&  apt-get -t stretch-backports install -y --no-install-recommends \
                  pypy-dev \
                  pypy-setuptools \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  update-alternatives --install /usr/bin/python python /usr/bin/pypy 1

RUN easy_install-pypy pip wheel virtualenv

ARG GIT_VERSION
LABEL com.bearstech.source.python=https://github.com/factorysh/docker-python/commit/${GIT_VERSION}

ARG GIT_DATE
LABEL com.bearstech.date.python=${GIT_DATE}
