FROM bearstech/debian:stretch

ENV LANG=C.UTF-8

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                  python2.7 \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

ARG GIT_VERSION
LABEL com.bearstech.source.python=https://github.com/factorysh/docker-python/commit/${GIT_VERSION}

