FROM bearstech/debian:stretch

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        python3-dev \
        python3-pip \
        python3-venv \
    && rm -rf /var/lib/apt/lists/*
